<?php

const TEXTO_REGISTRO_ACTIVO = 'si';
const TEXTO_REGISTRO_INACTIVO = 'no';
const REGISTRO_RELACIONADO = '23000';

define('GUARDAR_MENU_SESSION',(bool) $_ENV['GUARDAR_MENU_SESSION']);
define('GUARDAR_ACCIONES_SESSION',(bool) $_ENV['GUARDAR_ACCIONES_SESSION']);

define('GRUPO_PROGRAMADORES_ID',(int) $_ENV['GRUPO_PROGRAMADORES_ID']);
define('GRUPO_ADMINISTRADORES_ID',(int) $_ENV['GRUPO_ADMINISTRADORES_ID']);